version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: door_manufacturing_db_dev
    environment:
      POSTGRES_DB: ${DB_NAME:-door_manufacturing}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backend/database/init:/docker-entrypoint-initdb.d
    networks:
      - door_network_dev

  # Redis for caching and queues
  redis:
    image: redis:7-alpine
    container_name: door_manufacturing_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - door_network_dev

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  door_network_dev:
    driver: bridge
